# Telegram info
TOKEN = '825727999:AAGTZPK2TRRWZID-rxXicGpFeAbd8dbMyrk'
BOT_USERNAME = "bot_username"
CONTACT_ACC_USERNAME = "google"
ID_POST_CHANNEL = -243828263
ID_MANAGE_CHANNEL = -243828263
ALLOWED_GROUP_CHATS = {ID_POST_CHANNEL, ID_MANAGE_CHANNEL}

# Payment
PAYMENT_PROVIDER = '410694247:TEST:1496cc79-d856-44c4-9aa0-0271d717ca9f'

# Files' path
P_ACTIONS = "./data/actions.txt"
P_CATEGORIES = "./data/categories.json"
P_CATEGORIES_R = "./data/categories_r.json"  # relationships
P_D_POSTS = "./data/dposts.json"
P_POSTS = "./data/posts.json"
P_ORDERS = "./data/orders.json"
P_OWNERSHIPS = "./data/ownerships.json"
P_USERS = "./data/users.json"

# Letters limits
FREELANCE_TITLE_LETTERS_LIMIT = 50
FREELANCE_DESCRIPTION_LETTERS_LIMIT = 500
FREELANCE_MEMO_LETTERS_LIMIT = 350
FREELANCE_CONTACTS_LETTERS_LIMIT = 100
CUSTOMER_TITLE_LETTERS_LIMIT = 50
CUSTOMER_DESCRIPTION_LETTERS_LIMIT = 500
CUSTOMER_MEMO_LETTERS_LIMIT = 350
CUSTOMER_CONTACTS_LETTERS_LIMIT = 100
VERIFICATION_ABOUT_LETTERS_LIMIT = 500
VERIFICATION_LINKS_LETTERS_LIMIT = 500


# db info
DB_NAME = 'database'
DB_USER = 'db_user'
DB_HOST = 'localhost'
DB_PASS = 'mypassword'

# text
W_COMPLETE_EDITING = "Закончите редактирование"


# NOT TO EDIT
URL_CONTACT_ACC = "https://t.me/" + CONTACT_ACC_USERNAME
CANT_READ_FILE_EXCEPTIONS = FileNotFoundError, FileExistsError, NotADirectoryError
POSSIBLE_COME_TO_SIDEMENU = {1, 4, 100}
POSSIBLE_COME_TO_PAIDSERVICES = {1, 75}
POSSIBLE_COME_TO_CREATEFREELANCEPOST = {2, 4}
POSSIBLE_COME_TO_CATEGORY_FR = {4, 5}
POSSIBLE_COME_TO_CATEGORY_BACK_FR = {4}